security:
  jwt:
    secret-key: 96RKSARScRdM1KvZV9CyHngjXbanXytW5OIq8V5eQ/KyVB7XbaN9rhTG+87aZwoNAPHgguyd8R4VKUsh8MkIiw==
    expiration-time: 3600 # Access Token: 1 hour
    refresh-expiration-time: 8640000 # Refresh Token: 100 days
server:
  port: 8080
  servlet:
    context-path: /api/v1
  address: 192.168.0.104

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true # Start pagination page from 1
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=quan-ly-dien-thoai;encrypt=false"
    username: "sa"
    password: "!Nguyenvu123"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs.html
