security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 900 # Access Token: 1 hour
    refresh-expiration-time: 8640000 # Refresh Token: 100 days
server:
  port: 8080
  servlet:
    context-path: /
  # address: 192.168.0.104

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true # Start pagination page from 1
  # datasource:
  #   url: "jdbc:sqlserver://localhost:1433;databaseName=quan-ly-dien-thoai;encrypt=false"
  #   username: "sa"
  #   password: "!Nguyenvu123"
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        auto_quoted_keyword: true
        globally_quoted_identifiers: true
springdoc:
  api-docs:
    path: /api-docs
