server:
  port: 8080
  servlet:
    context-path: /api

spring:
    datasource:
        url: "jdbc:sqlserver://localhost:1433;databaseName=quanlydt;encrypt=false"
        username: "sa"
        password: "!Nguyenvu123"
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
              dialect: org.hibernate.dialect.SQLServerDialect