security:
  jwt:
    secret-key: 96RKSARScRdM1KvZV9CyHngjXbanXytW5OIq8V5eQ/KyVB7XbaN9rhTG+87aZwoNAPHgguyd8R4VKUsh8MkIiw==
    expiration-time: 86400000

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=quanlydt;encrypt=false"
    username: "sa"
    password: "!Nguyenvu123"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
